language: python
sudo: false
python:
  - '2.7'
  - pypy
deploy:
  provider: pypi
  user: beni
  password:
    secure: ib4iaqycgcF3ijSC...
  on:
    tags: true
install:
  - pip install -r requirements.txt
  - python setup.py install
  - pip install coveralls
script:
  - nosetests
after_success: coveralls